/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminologyRouteImport } from './routes/terminology'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIdRouteImport } from './routes/patient.$id'
import { Route as ApiTerminologySplatRouteImport } from './routes/api/terminology/$'
import { Route as ApiFhirSplatRouteImport } from './routes/api/fhir/$'

const TerminologyRoute = TerminologyRouteImport.update({
  id: '/terminology',
  path: '/terminology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminologySplatRoute = ApiTerminologySplatRouteImport.update({
  id: '/api/terminology/$',
  path: '/api/terminology/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFhirSplatRoute = ApiFhirSplatRouteImport.update({
  id: '/api/fhir/$',
  path: '/api/fhir/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terminology': typeof TerminologyRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
  '/api/terminology/$': typeof ApiTerminologySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terminology': typeof TerminologyRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
  '/api/terminology/$': typeof ApiTerminologySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terminology': typeof TerminologyRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
  '/api/terminology/$': typeof ApiTerminologySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terminology'
    | '/patient/$id'
    | '/api/fhir/$'
    | '/api/terminology/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terminology'
    | '/patient/$id'
    | '/api/fhir/$'
    | '/api/terminology/$'
  id:
    | '__root__'
    | '/'
    | '/terminology'
    | '/patient/$id'
    | '/api/fhir/$'
    | '/api/terminology/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TerminologyRoute: typeof TerminologyRoute
  PatientIdRoute: typeof PatientIdRoute
  ApiFhirSplatRoute: typeof ApiFhirSplatRoute
  ApiTerminologySplatRoute: typeof ApiTerminologySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminology': {
      id: '/terminology'
      path: '/terminology'
      fullPath: '/terminology'
      preLoaderRoute: typeof TerminologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminology/$': {
      id: '/api/terminology/$'
      path: '/api/terminology/$'
      fullPath: '/api/terminology/$'
      preLoaderRoute: typeof ApiTerminologySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fhir/$': {
      id: '/api/fhir/$'
      path: '/api/fhir/$'
      fullPath: '/api/fhir/$'
      preLoaderRoute: typeof ApiFhirSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TerminologyRoute: TerminologyRoute,
  PatientIdRoute: PatientIdRoute,
  ApiFhirSplatRoute: ApiFhirSplatRoute,
  ApiTerminologySplatRoute: ApiTerminologySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
