/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIdRouteImport } from './routes/patient.$id'
import { Route as ApiTerminologySplatRouteImport } from './routes/api/terminology/$'
import { Route as ApiFhirSplatRouteImport } from './routes/api/fhir/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminologySplatRoute = ApiTerminologySplatRouteImport.update({
  id: '/api/terminology/$',
  path: '/api/terminology/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFhirSplatRoute = ApiFhirSplatRouteImport.update({
  id: '/api/fhir/$',
  path: '/api/fhir/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
  '/api/terminology/$': typeof ApiTerminologySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
  '/api/terminology/$': typeof ApiTerminologySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
  '/api/terminology/$': typeof ApiTerminologySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patient/$id' | '/api/fhir/$' | '/api/terminology/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patient/$id' | '/api/fhir/$' | '/api/terminology/$'
  id: '__root__' | '/' | '/patient/$id' | '/api/fhir/$' | '/api/terminology/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientIdRoute: typeof PatientIdRoute
  ApiFhirSplatRoute: typeof ApiFhirSplatRoute
  ApiTerminologySplatRoute: typeof ApiTerminologySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminology/$': {
      id: '/api/terminology/$'
      path: '/api/terminology/$'
      fullPath: '/api/terminology/$'
      preLoaderRoute: typeof ApiTerminologySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fhir/$': {
      id: '/api/fhir/$'
      path: '/api/fhir/$'
      fullPath: '/api/fhir/$'
      preLoaderRoute: typeof ApiFhirSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientIdRoute: PatientIdRoute,
  ApiFhirSplatRoute: ApiFhirSplatRoute,
  ApiTerminologySplatRoute: ApiTerminologySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
